# Generated by Django 2.1.2 on 2018-10-10 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='title')),
                ('last_name', models.TextField(verbose_name='Description')),
                ('standard', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
